# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-qv-kcO4ZeQVMr3WEuQ_yzeUZVfHvoM
"""

import streamlit as st

st.title("🎬 AI Movie Recommendation Assistant")
st.write("Answer a few questions and I'll recommend some movies for you!")

# Dataset
movies = [
    {"title": "Inception", "genre": "sci-fi", "actor": "Leonardo DiCaprio", "mood": "adventurous"},
    {"title": "La La Land", "genre": "romance", "actor": "Emma Stone", "mood": "happy"},
    {"title": "The Avengers", "genre": "action", "actor": "Robert Downey Jr.", "mood": "adventurous"}
]

# User inputs
genre = st.text_input("Preferred genre?").lower()
actor = st.text_input("Favorite actor?").lower()
mood = st.text_input("Your mood?").lower()

# Recommendation logic
if st.button("Get Recommendations"):
    recs = [m["title"] for m in movies if genre in m["genre"].lower()
                                    or actor in m["actor"].lower()
                                    or mood in m["mood"].lower()]
    if recs:
        st.write("We recommend:")
        for r in recs[:3]:
            st.write(f" - {r}")
    else:
        st.write("No matches found. Try different answers.")

!pip install streamlit